name: Build Pull Request

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout work branch
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Run build
              run: npm run build:dev
            - name: Run Tests
              run: npm test
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
